from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.scatter import RuleScatter
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class ActivityShikigamiAssets: 


	# Click Rule Assets
	# 
	C_CL_SELECT_EASY = RuleClick(roi_front=(1166,171,71,63), roi_back=(1166,171,71,63), name="cl_select_easy")
	# 
	C_CL_SELECT_HARD = RuleClick(roi_front=(1121,340,71,63), roi_back=(1121,340,71,63), name="cl_select_hard")
	# 
	C_RANDOM_CLOSE_AUTOFIGHT = RuleClick(roi_front=(1204,88,76,449), roi_back=(1204,88,76,449), name="random_close_autofight")


	# Image Rule Assets
	# 上锁图标 
	I_LOCK = RuleImage(roi_front=(898,647,24,27), roi_back=(759,628,330,86), threshold=0.7, method="Template matching", file="./tasks/ActivityShikigami/as/climb/as_lock.png")
	# 还未上锁图片 
	I_UNLOCK = RuleImage(roi_front=(899,648,24,23), roi_back=(752,625,313,92), threshold=0.7, method="Template matching", file="./tasks/ActivityShikigami/as/climb/as_unlock.png")
	# 活动爬塔标志 
	I_CLIMB_MODE_PASS = RuleImage(roi_front=(1143,544,21,21), roi_back=(1118,510,119,186), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/climb/as_climb_mode_pass.png")
	# 体力爬塔标志 
	I_CLIMB_MODE_AP = RuleImage(roi_front=(151,18,132,40), roi_back=(140,5,156,58), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/climb/as_climb_mode_ap.png")
	# 切换按键 
	I_CLIMB_MODE_SWITCH = RuleImage(roi_front=(1233,547,29,26), roi_back=(1174,511,104,82), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/climb/as_climb_mode_switch.png")
	# 100体爬塔标志 
	I_CLIMB_MODE_AP100 = RuleImage(roi_front=(151,18,132,40), roi_back=(140,5,156,58), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/climb/as_climb_mode_ap100.png")
	# 体力爬塔阵容解锁 
	I_AP_UNLOCK = RuleImage(roi_front=(802,653,27,27), roi_back=(790,642,49,47), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/climb/as_ap_unlock.png")
	# 体力爬塔阵容锁定 
	I_AP_LOCK = RuleImage(roi_front=(802,653,27,27), roi_back=(790,642,49,47), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/climb/as_ap_lock.png")
	# 活动通用挑战图标 
	I_ACT_FIRE = RuleImage(roi_front=(1131,601,91,40), roi_back=(1100,550,160,140), threshold=0.8, method="Template matching", profile="More", file="./tasks/ActivityShikigami/as/climb/as_act_fire.png")
	# boss挑战标志 
	I_AS_BOSS_FIRE = RuleImage(roi_front=(1130,590,92,47), roi_back=(1080,530,192,190), threshold=0.8, method="Template matching", profile="More", file="./tasks/ActivityShikigami/as/climb/as_as_boss_fire.png")
	# 使用五倍卷 
	I_FIGHT_PENTA_USE = RuleImage(roi_front=(867,650,31,30), roi_back=(755,631,330,86), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/climb/climb_fight_penta_use.png")
	# 不使用五倍卷 
	I_FIGHT_PENTA_DISUSE = RuleImage(roi_front=(873,651,32,32), roi_back=(866,644,47,47), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/climb/climb_fight_penta_disuse.png")
	#  
	I_CHECK_CLIMB_HARD = RuleImage(roi_front=(615,413,67,67), roi_back=(610,408,77,77), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/climb/climb_check_climb_hard.png")
	#  
	I_CHECK_CLIMB_EASY = RuleImage(roi_front=(615,413,67,67), roi_back=(610,408,77,77), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/climb/climb_check_climb_easy.png")
	#  
	I_USELESS_MESSAGE_CLOSE = RuleImage(roi_front=(1171,95,31,30), roi_back=(1042,68,179,170), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/climb/climb_useless_message_close.png")
	#  
	I_AUTOFIGHT = RuleImage(roi_front=(533,98,207,46), roi_back=(470,73,330,86), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/climb/climb_autofight.png")
	# 未选御魂 
	I_ORCHI_SELECT_NONE = RuleImage(roi_front=(180,520,38,39), roi_back=(0,505,240,65), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/climb/climb_orchi_select_none.png")
	# 百体活动挑战按钮
	I_AP100_FIRE = RuleImage(roi_front=(1133,598,92,44), roi_back=(1100,550,160,140), threshold=0.8, method="Template matching", profile="More", file="./tasks/ActivityShikigami/as/climb/ap100_fire.png")
	# 百体阵容未锁定
	I_AP100_UNLOCK = RuleImage(roi_front=(748,651,27,28), roi_back=(735,640,54,48), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/climb/ap100_unlock.png")
	# 百体阵容已锁定
	I_AP100_LOCK = RuleImage(roi_front=(748,651,27,28), roi_back=(735,640,54,48), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/climb/ap100_lock.png")


	# Ocr Rule Assets
	# 活动门票的剩余检测 
	O_REMAIN_PASS = RuleOcr(roi=(756,17,88,31), area=(756,17,88,31), mode="Digit", method="Default", keyword="", name="remain_pass")
	# boss剩余攻击次数 
	O_REMAIN_BOSS = RuleOcr(roi=(1169,668,70,30), area=(1169,668,70,30), mode="DigitCounter", method="Default", keyword="", name="remain_boss")
	# 100体活动门票检测 
	O_REMAIN_AP100 = RuleOcr(roi=(1107,20,104,40), area=(1107,20,104,40), mode="Digit", method="Default", keyword="", name="remain_ap100")
	# 五倍卷剩余数量 
	O_REMAIN_PENTA_PASS = RuleOcr(roi=(949,13,90,38), area=(949,13,90,38), mode="Digit", method="Default", keyword="", name="remain_penta_pass")
	# 剩余体力门票 
	O_REMAIN_AP_PASS = RuleOcr(roi=(746,13,106,42), area=(746,13,106,42), mode="Digit", method="Default", keyword="", name="remain_ap_pass")


	# Image Rule Assets
	# 进入古迹演武（体力）
	I_TO_BATTLE_MAIN = RuleImage(roi_front=(219,254,103,30), roi_back=(190,230,160,83), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/climb/as_to_battle_main.png")
	# 进入首领战斗页面 
	I_TO_BATTLE_BOSS = RuleImage(roi_front=(125,449,88,58), roi_back=(97,402,145,138), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/climb/as_to_battle_boss.png")
	# 从爬塔主界面进入式神录 
	I_BATTLE_MAIN_TO_RECORDS = RuleImage(roi_front=(1015,560,39,42), roi_back=(674,539,439,157), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/climb/as_battle_main_to_records.png")
	# 爬塔主界面标志 
	I_CHECK_BATTLE_PASS = RuleImage(roi_front=(151,18,134,40), roi_back=(141,0,157,67), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/climb/as_check_battle_pass.png")
	#  
	I_TO_BATTLE_CLIMB = RuleImage(roi_front=(68,98,140,33), roi_back=(32,83,247,97), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/climb/climb_to_battle_climb.png")
	#  
	I_CHECK_CLIMB_MAIN = RuleImage(roi_front=(151,18,134,40), roi_back=(141,0,157,67), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/climb/climb_check_climb_main.png")
	# 进入刹那试炼（百体）
	I_TO_BATTLE_AP100 = RuleImage(roi_front=(403,459,103,29), roi_back=(373,435,163,78), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/climb/to_battle_ap100.png")


	# Click Rule Assets
	# description
	C_FG_RANDOM_LEFT = RuleClick(roi_front=(17,84,104,356), roi_back=(17,81,106,365), name="fg_random_left")
	# description
	C_FG_RANDOM_RIGHT = RuleClick(roi_front=(1133,88,131,361), roi_back=(1131,84,133,363), name="fg_random_right")
	# description
	C_FG_RANDOM_TOP = RuleClick(roi_front=(126,66,989,58), roi_back=(123,65,991,58), name="fg_random_top")
	# description
	C_FG_RANDOM_BOTTOM = RuleClick(roi_front=(196,598,581,78), roi_back=(194,597,583,81), name="fg_random_bottom")
	# description
	C_FG_RANDOM_ALL = RuleClick(roi_front=(42,94,1207,543), roi_back=(42,94,1207,543), name="fg_random_all")


	# Image Rule Assets
	# 上锁图标 
	I_FG_LOCK = RuleImage(roi_front=(896,654,27,28), roi_back=(884,642,52,48), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/fakegod/as_lock.png")
	# 阵容未锁定 
	I_FG_UNLOCK = RuleImage(roi_front=(896,654,27,28), roi_back=(884,642,52,48), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/fakegod/as_unlock.png")
	# 磐长故地挑战页标志
	I_FG_CLIMB_MODE_PASS = RuleImage(roi_front=(151,18,132,40), roi_back=(140,5,156,58), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/fakegod/as_climb_mode_pass.png")
	# 体力爬塔标志 
	I_FG_CLIMB_MODE_AP = RuleImage(roi_front=(1093,542,22,25), roi_back=(1055,495,202,219), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/fakegod/as_climb_mode_ap.png")
	# 百体爬塔标志 
	I_FG_CLIMB_MODE_AP100 = RuleImage(roi_front=(1186,665,22,25), roi_back=(1055,495,202,219), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/fakegod/as_climb_mode_ap100.png")
	# 体力阵容未锁定 
	I_FG_AP_UNLOCK = RuleImage(roi_front=(779,648,31,30), roi_back=(686,610,313,92), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/fakegod/as_ap_unlock.png")
	# 体力阵容已锁定 
	I_FG_AP_LOCK = RuleImage(roi_front=(779,648,31,30), roi_back=(686,610,313,92), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/fakegod/as_ap_lock.png")
	# 活动挑战按钮 
	I_FG_ACT_FIRE = RuleImage(roi_front=(1133,591,91,40), roi_back=(1100,550,160,140), threshold=0.8, method="Template matching", profile="More", file="./tasks/ActivityShikigami/as/fakegod/as_act_fire.png")


	# Ocr Rule Assets
	# 体力数量（兼容x.x万） 
	O_FG_REMAIN_AP = RuleOcr(roi=(1123,24,95,34), area=(1123,24,95,34), mode="Quantity", method="Default", keyword="", name="fg_remain_ap")
	# 活动门票数量 
	O_FG_REMAIN_PASS = RuleOcr(roi=(1104,24,105,34), area=(1104,24,105,34), mode="Digit", method="Default", keyword="", name="fg_remain_pass")
	# 首领剩余次数 
	O_FG_REMAIN_BOSS = RuleOcr(roi=(1169,668,70,30), area=(1169,668,70,30), mode="DigitCounter", method="Default", keyword="", name="fg_remain_boss")
	# 百体活动次数 
	O_FG_REMAIN_AP100 = RuleOcr(roi=(922,21,112,39), area=(913,8,131,62), mode="Digit", method="Default", keyword="", name="fg_remain_ap100")
	# 百体入口 
	O_FG_ENTER_AP100 = RuleOcr(roi=(67,99,92,359), area=(67,99,92,359), mode="Full", method="Default", keyword="雪山修行", name="fg_enter_ap100")


	# Image Rule Assets
	# 庭院进入活动 
	I_FG_MAIN_GOTO_ACT = RuleImage(roi_front=(1188,304,35,28), roi_back=(1164,134,83,393), threshold=0.7, method="Template matching", file="./tasks/ActivityShikigami/as/fakegod/as_main_goto_act.png")
	# 跳过按钮 
	I_FG_SKIP_BUTTON = RuleImage(roi_front=(1159,37,51,22), roi_back=(1141,27,86,43), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/fakegod/as_skip_button.png")
	# 进入磐长故地地图
	I_FG_TO_BATTLE_MAIN = RuleImage(roi_front=(814,459,108,30), roi_back=(784,435,167,80), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/fakegod/as_to_battle_main.png")
	# 进入首领战 
	I_FG_TO_BATTLE_BOSS = RuleImage(roi_front=(935,250,35,123), roi_back=(876,165,234,327), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/fakegod/as_to_battle_boss.png")
	# 首领界面标志 
	I_FG_CHECK_BATTLE_BOSS = RuleImage(roi_front=(151,18,129,46), roi_back=(141,0,151,85), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/fakegod/as_check_battle_boss.png")
	# 进入式神录 
	I_FG_BATTLE_MAIN_TO_RECORDS = RuleImage(roi_front=(1015,560,39,42), roi_back=(674,539,439,157), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/fakegod/as_battle_main_to_records.png")
	# 磐长故地地图标志
	I_FG_AS_CHECK_MAIN_2 = RuleImage(roi_front=(591,2,139,40), roi_back=(573,0,175,60), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/fakegod/as_as_check_main_2.png")
	# 打开暗黑地图 
	I_FG_AS_OPEN_EYE = RuleImage(roi_front=(1198,300,60,54), roi_back=(1146,253,134,217), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/fakegod/as_as_open_eye.png")
	# 地图定位按钮 
	I_FG_AS_LOCATE = RuleImage(roi_front=(1212,394,34,36), roi_back=(1146,253,134,217), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/fakegod/as_as_locate.png")
	# 暗黑地图标志 
	I_FG_AS_CLOSE_EYE = RuleImage(roi_front=(1197,297,63,57), roi_back=(1146,253,134,217), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/fakegod/as_as_close_eye.png")
	# 地图据点的战斗文字（避开头像及光效）
	I_FG_AS_TO_PASS = RuleImage(roi_front=(665,415,15,32), roi_back=(0,60,1150,600), threshold=0.78, method="Multi-scale template matching", file="./tasks/ActivityShikigami/as/fakegod/as_as_to_pass.png")
	# 进入体力爬塔 
	I_FG_TO_BATTLE_AP = RuleImage(roi_front=(825,321,39,139), roi_back=(720,255,238,269), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/fakegod/as_to_battle_ap.png")
	# 磐长故地左侧进入古迹演武（体力）
	I_FG_MAP_TO_AP = RuleImage(roi_front=(74,149,95,30), roi_back=(65,140,220,50), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/fakegod/fg_map_to_ap.png")
	# 磐长故地左侧进入刹那试炼（百体）
	I_FG_MAP_TO_AP100 = RuleImage(roi_front=(74,244,95,30), roi_back=(65,235,220,50), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/fakegod/fg_map_to_ap100.png")


	# Image Rule Assets
	# 庭院进入活动 
	I_MAIN_GOTO_ACT = RuleImage(roi_front=(1185,457,43,43), roi_back=(1164,134,83,393), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/page/as_main_goto_act.png")
	# 右上跳过按钮 
	I_SKIP_BUTTON = RuleImage(roi_front=(1159,37,51,22), roi_back=(1141,27,86,43), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/page/as_skip_button.png")
	# 活动主界面标志 
	I_CHECK_BATTLE_MAIN = RuleImage(roi_front=(151,18,132,40), roi_back=(140,5,156,58), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/page/as_check_battle_main.png")
	# 确认跳过 
	I_CONFIRM_SKIP = RuleImage(roi_front=(707,442,137,38), roi_back=(656,397,231,124), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/page/as_confirm_skip.png")
	# 活动签到附属页面关闭按钮 
	I_ACTIVITY_SIGNIN_CLOSE = RuleImage(roi_front=(1137,179,40,32), roi_back=(1113,150,94,85), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/page/as_activity_signin_close.png")


